Create 01-significance-of-sutera's-existence.md
SuteraVR/Specifications pull request #29
Opened 2024-07-13 09:43 UTC by See2et

2024-07-13 09:44 UTC, See2et commented
方向性が難しい...コメントください！

2024-07-13 09:48 UTC, LegitYew0108 commented
質問-回答形式にするよりも、堂々と「Suteraの存在意義はこれです！」って言うべきな気がした

2024-07-13 10:00 UTC, AsPulse requested changes
概ね同意！
質問-回答を書くのはいいけど、これだ！と言い切ってから下に載せよう

2024-07-13 10:02 UTC, See2et commented
うにゃーやっぱそうだよねー！なおします！

2024-07-13 11:39 UTC, AsPulse requested changes
多くてごめんね～～～～～

2024-07-13 11:39 UTC, AsPulse commented on sutera/01-significance-of-sutera's-existence.md
> +## Q&A
「FAQ」、または「よくある質問」の方がいいかも
Q&Aってあんまり正式な場所で言わない……

2024-07-13 11:39 UTC, AsPulse commented on sutera/01-significance-of-sutera's-existence.md
> +Suteraチームのメンバーの多くはVRChatやResoniteなどの既存プラットフォームで思い出を築いてきた人たちばかりで、プロジェクトの方針としても個々のメンバーの感情論としてもそれらを打倒・否定することを目的とはしていません。
```suggestion
Suteraチームには、VRChatやResoniteなどの既存プラットフォームで思い出を築いてきたメンバーが多くいます。  
プロジェクトの方針としても個々のメンバーの感情論としてもそれらを打倒・否定することを目的とはしていません。
```
Suggestionは日本語の修正です
あとはVRChat, Resoniteの名前出してよさそう……？ (その判断はSee2etに任せます)

2024-07-13 11:39 UTC, AsPulse commented on sutera/01-significance-of-sutera's-existence.md
> +### 既存のサービスは持続可能的ではないのか？
```suggestion
### 既存のサービスは持続可能ではないのか？
```

2024-07-13 11:39 UTC, AsPulse commented on sutera/01-significance-of-sutera's-existence.md
> +SuteraはOSSであるため、ユーザーが望む形に沿ったSocial-VRを実現し続けることができます。
```suggestion
Suteraはオープンソースプロジェクトであるため、ユーザーが望む形に沿ったSocial-VRを実現し続けることができます。
```
SuteraはOSS、Open-source **Software** じゃないよ.ᐟ.ᐟ.ᐟ

2024-07-13 11:39 UTC, AsPulse commented on sutera/01-significance-of-sutera's-existence.md
> +- サーバー: [SuteraVR/VanilaComponents](https://github.com/SuteraVR/VanilaComponents)
```suggestion
- Bloom (サーバー): [SuteraVR/VanilaComponents](https://github.com/SuteraVR/VanilaComponents)
```

2024-07-13 11:39 UTC, AsPulse commented on sutera/01-significance-of-sutera's-existence.md
> +Suteraは[SuteraVR/Specifications](https://github.com/SuteraVR/Specifications)に記述される仕様書が本体です。
```suggestion
Suteraは、仕様書であるこのドキュメントそのものが本体です。
```
このファイルもSpecificationの中なので……

2024-07-13 11:39 UTC, AsPulse commented on sutera/01-significance-of-sutera's-existence.md
> +Suteraは分散型Social-VRを実現することにより、持続可能な仮想空間・メタバースを目指します。
```suggestion
Suteraは分散型Social-VRを実現することにより、持続可能な仮想空間・メタバースの実現を目指します。
```

2024-07-13 11:48 UTC, See2et commented
@AsPulse @LegitYew0108 再度確認おねがいします！

2024-07-14 01:46 UTC, AsPulse commented
う～～～～ん…………
文章は整ってるんだけど、ちょっとだけ読みづらさが！
新・物理入門を呼んでる気分になる

2024-07-14 01:58 UTC, See2et commented
むむむ...どうしたら読みやすくなるかにゃ

2024-07-14 13:11 UTC, See2et commented
@AsPulse 相談したいにゃ～～

2024-07-17 20:27 UTC, See2et commented
メモ
- Social-VRとは？
- 分散型とは？
- 既存のプラットフォームは～～～

2024-07-20 08:04 UTC, AsPulse commented
疑問符禁止はないほうがいいな……
出先だから戻ったらルール直しますね（あるいはPR待ってるよはーとまーく以下略

2024-07-21 09:42 UTC, See2et commented
@AsPulse Social-VRがRelay-VRに直されてまう！泣いちゃう！

2024-07-21 09:56 UTC, AsPulse commented
わああ
ちょっとまってね

2024-07-24 08:22 UTC, AsPulse requested changes
今気付いたんだけど、`###`と`##`の関係がおかしいな……
あと何か他のを見つけちゃわない限りこれで最後……

2024-07-24 09:38 UTC, See2et commented
こんどこそ!

2024-07-24 09:46 UTC, AsPulse approved these changes
よおおおおくがんばりましたあああああえらいえらいえらいえらい

2024-07-24 09:48 UTC, See2et commented
やったぜ！！！！！！！すかっしゅあんどまーーーーーーーじ！！！！！！

2024-07-24 09:48 UTC, merged