docs(idea/object-storage): what is Object-Storage
SuteraVR/Specifications pull request #31
Opened 2024-07-13 11:01 UTC by HMasataka

2024-07-13 12:08 UTC, See2et requested changes
句点(。)を付けて欲しいです！

2024-07-13 12:15 UTC, See2et commented
@AsPulse 内容は良さそうなので、文章表現とかのチェックお願いします！

2024-07-13 12:16 UTC, See2et requested changes

2024-07-13 12:16 UTC, See2et commented on object-storage/01-what-is-object-storage.md
> +  * まれではありますが同じデータの複製を持ってる全てのbloomが同時に停止するとデータがロストします
ステラ→Suteraに置換して欲しいです！

2024-07-13 12:17 UTC, HMasataka commented on object-storage/01-what-is-object-storage.md
> +  * まれではありますが同じデータの複製を持ってる全てのbloomが同時に停止するとデータがロストします
直しました

3bccc082cc37aa7091249e3a1a453488384ad0aa

2024-07-13 12:18 UTC, HMasataka commented
> 句点(。)を付けて欲しいです！
366ec7aa5f9ff34c4fb901cf0c3d99bd2f148a5a

2024-07-14 00:54 UTC, See2et approved these changes

2024-07-14 01:44 UTC, AsPulse requested changes
全体的にあっさりとしすぎ……というか「役割」の範疇を越えているように思います
- Object-Storageの「役割」には、非ユーザー依存データの自動的な管理のみが該当しますね
- その後に、自動的なレプリケーションによる保管の説明
- バックアップとして手動でBloomを指定したレプリケーションができることの説明

と組みたてましょう！
一つの章ごとがスカスカになってしまったとしても、あとで情報がだんだん増えていき、最終的にはちょうどよくなると思いますので……

2024-07-14 01:44 UTC, AsPulse commented on object-storage/01-what-is-object-storage.md
> +* 非ユーザー依存データはSuteraネットワーク内のObject-Storageコンポーネントのうち、自動的に複数箇所へと保管されます。
```suggestion
* 非ユーザー依存データは、自動的に選択された複数箇所のObject-Storageコンポーネントへ保管されます。
```
あんまり～の、～のと連続すると読みづらいので……！

2024-07-14 01:44 UTC, AsPulse commented on object-storage/01-what-is-object-storage.md
> +* データを保持しているBloomが何かしらの理由で停止した場合、Suteraネットワークは同じデータを持っている他のBloomから別のBloomへデータをコピーします。
```suggestion
* データを保管しているBloomが何かしらの理由で停止した場合、Suteraネットワークは同じデータを持っている他のBloomから別のBloomへデータをコピーします。
```
上で保管と言ったので保管と言いましょう

2024-07-14 02:07 UTC, HMasataka commented
@AsPulse 

ひとまずセクション分けしてみました
https://github.com/SuteraVR/Specifications/pull/31/commits/4635849676255f8ec2a67182faecb65a7c9a47d5

> 全体的にあっさりとしすぎ

現段階で各セクションの内容をもうちょっと盛っていった方が良いですか？

2024-07-14 02:21 UTC, AsPulse commented
セクション分けいい感じです！
内容は盛れるならそうしてくれると嬉しいんですが……書くことがあまり見当たらなければスカスカでも大丈夫です！
いまDiscordの方に送ったここらへんを気をつけてくれるともう少し良い感じかなと思います: [SuteraVR - ステラ - / #random](https://discord.com/channels/1164196413945688114/1164196416126717994/1261869440178589696)

2024-07-14 02:32 UTC, HMasataka commented
ありがとうございます
では内容に関しては書きたいことが増えてきたときにまた書いていこうと思います

Discord参考に箇条書きやめて文章形式になるように調整しました
b6cb4079c2b91fb17a4f08821e38611050559090

2024-07-14 03:38 UTC, AsPulse requested changes
箇条書きしてると気付きにくいのですが……
markdownだと、1つの改行は改行として出力されません！

前行の最後尾に半角スペースを二つつけると、小さな改行ができます。
```
あいうえお[半角スペース][半角スペース]
かきくけこ
```

段落を区切るような大きな改行は、1行あけるとできます。
```
あいうえお

かきくけこ
```

これを考慮して少し直してみてほしいです！

2024-07-14 03:38 UTC, AsPulse commented on object-storage/01-what-is-object-storage.md
> +大事なワールド等のデータは指定の(self-hostedの)Bloomにコピーを持たせるという運用もできます。
まず「自動的なレプリケーションでのデータロストのリスクに備え、非ユーザー依存のデータは、Bloomを指定してコピーすることもできる」という**事実のみを述べる形式** にしましょう！

その後に機能の活用例として、「思い出深いワールドは自分でホストするBloomでも保管しておく」のように書きましょう

二つ混ぜちゃうとちょっとごちゃごちゃしてます！

2024-07-14 04:01 UTC, HMasataka commented
> 箇条書きしてると気付きにくいのですが…… markdownだと、1つの改行は改行として出力されません！
> 
> 前行の最後尾に半角スペースを二つつけると、小さな改行ができます。
> 
> ```
> あいうえお[半角スペース][半角スペース]
> かきくけこ
> ```
> 
> 段落を区切るような大きな改行は、1行あけるとできます。
> 
> ```
> あいうえお
> 
> かきくけこ
> ```
> 
> これを考慮して少し直してみてほしいです！

すみません
改行されるように修正しました
6a4b19c2d0c8e11586233440538c6d35ebae8d1a

2024-07-14 04:02 UTC, HMasataka commented on object-storage/01-what-is-object-storage.md
> +大事なワールド等のデータは指定の(self-hostedの)Bloomにコピーを持たせるという運用もできます。
事実と活用例分けてみました

https://github.com/SuteraVR/Specifications/pull/31/commits/7c5a4b8604f65d74ee93693fdbf2c9d860359e96

2024-07-14 05:08 UTC, AsPulse approved these changes
Looks good to me

2024-07-14 07:17 UTC, See2et approved these changes
LGTM!

2024-07-14 07:17 UTC, merged