Docs/differences in handling user dependent and non user dependent data
SuteraVR/Specifications pull request #32
Opened 2024-07-14 14:39 UTC by kokonoha

2024-07-15 07:33 UTC, AsPulse requested changes
5行目以降常体にしてください……！

2024-07-15 07:33 UTC, AsPulse commented on package/14_Differences-in-handling-user-dependent-and-non-user-dependent-data_ja-jp.md
> +非ユーザー依存データはワールドを主とする、ユーザーが共有したSuteraネットワークが保持しているデータのことを指します。
別に間違ってはないんですが……
「Suteraネットワーク上でやりとりされるデータを2種類に分類した」というところから話を始めてほしいです.ᐟ.ᐟ.ᐟ
Object-storageで扱うデータをなるべく少なくしたいことから、「ユーザー依存データはObject-storageに保存しなくてもよいんだ」という発見にたどりつけるように読者を誘導してほしいです
( + なぜユーザー依存データをObject-Storageに保存しなくてもいいのか、を「セッションを開始した際に共有」みたいな言葉で済ませず、もう少し具体例などを用いた説明が欲しいです。)

2024-07-22 10:54 UTC, kokonoha commented
@AsPulse レビューして～

2024-08-16 15:36 UTC, kokonoha commented
@See2et この状態でSee2etにレビューしてもらえばいいんだよね？

2024-10-26 03:21 UTC, AsPulse requested changes

2024-10-26 03:21 UTC, AsPulse commented on package/14_Differences-in-handling-user-dependent-and-non-user-dependent-data_ja-jp.md
> +
```suggestion
そのためSuteraではやり取りされるデータをユーザー依存データと非ユーザー依存データの2種類に分類し、取り扱いに差を設けています。

```

2024-10-26 03:21 UTC, AsPulse commented on package/14_Differences-in-handling-user-dependent-and-non-user-dependent-data_ja-jp.md
> +
**1. ユーザー依存データが「アップロードしたユーザーしか利用しない」、非ユーザー依存データが「アップロードしたユーザー以外も利用する」は誤りです（まぁ利用するという言葉がどの範囲を指すかだけど……）**

  正確には、「アップロードしたユーザーがSuteraネットワークから離れれば不要になる」のがユーザー依存データ、「アップロードしたユーザーがSuteraネットワークから離れても必要である」のが非ユーザー依存データです

  > それにはユーザーが日々を過ごすWorldの存続も欠かせないと考えています。
  
  とありますが、これも「非ユーザー依存データである理由」という点では、ワールドの作者がいなくなっても**思い出の日々を過ごした**Worldが失われてはならない、という表現がより的確です

<br />

**2. 「アバターを主とする」「ワールドを主とする」という表現はやめて、「ユーザー依存データの例」「非ユーザー依存データの例」という小さいセクション内に切り出してください**。
  
  今後アバターやワールドだけじゃなくなる可能性があります。
  
  プロフィール情報などはユーザー依存データの他の例ですね。
  今はまだありませんがVRChatの「グループ」に相当するものができれば、それは非ユーザー依存データになる可能性があります（主催者のユーザー依存データになるかもだけど……）
  まとにかく、書き足せる構造にしておきましょう

2024-10-26 03:39 UTC, See2et commented on package/14_Differences-in-handling-user-dependent-and-non-user-dependent-data_ja-jp.md
> +
> ワールドの作者がいなくなっても思い出の日々を過ごしたWorldが失われてはならない
これを書くにあたって、実はどこにも「あの世界での思い出って大事だよね」と語っているページがないことに気付いた。
[Suteraの存在意義について](https://github.com/SuteraVR/Specifications/blob/51ecd8e9c14f14a8b1102f0b2f795a9aac8b296c/sutera/01-significance-of-sutera's-existence.md)はあくまで持続性にしか言及しておらず、もうちょい[HIKKYでのLT](https://docs.google.com/presentation/d/1B0YdXGwVic5E9Q0cI_KiEXNfG13Nsx-dzScKIhc9biI/edit?usp=sharing)で話したような内容を含めてもいい気がする
だいぶ主観的かつドキュメントっぽさからは外れるかもだけど...

2024-10-26 03:42 UTC, See2et commented on package/14_Differences-in-handling-user-dependent-and-non-user-dependent-data_ja-jp.md
> +
「なぜそこまでSuteraは持続性を追い求めるのか？」みたいなページがセクションがあってしかるべき、な気がしてきたんだけどどう思うかな

2024-10-26 13:24 UTC, AsPulse requested changes

2024-10-26 13:24 UTC, AsPulse commented on package/14_Differences-in-handling-user-dependent-and-non-user-dependent-data_ja-jp.md
> +[Suteraの存在意義について](sutera/01-significance-of-sutera's-existence.md)では「未来永劫Social-VRユーザーの居場所を保証・確約すること」を掲げています。それにはユーザーが日々を過ごす、あるいはそれ以上に**思い出の日々を過ごした**Worldの存続も欠かせないと考えています。
```suggestion
[Suteraの存在意義について](sutera/01-significance-of-sutera's-existence.md)では「未来永劫Social-VRユーザーの居場所を保証・確約すること」を掲げています。それにはユーザーが日々を過ごす、あるいはそれ以上に**思い出の日々を過ごした**Worldの存続も欠かせないと考えています。
```
これリンク相対パスなんで切れてます

2024-11-01 13:01 UTC, AsPulse approved these changes
lLGTM!

2024-12-04 17:02 UTC, merged