Docs/why sutera need to maintain idempotence
SuteraVR/Specifications pull request #48
Opened 2024-07-15 14:37 UTC by slotsu0809

2024-07-16 11:10 UTC, AsPulse requested changes
もう箇条書きが爆発してないし内容もしっかりしてるし、
図も参考文献もあるしでえらすぎるよ～～～.ᐟ.ᐟ.ᐟ

(PR名も `docs(idea/sutera): ....` に揃えてほしいです)

2024-07-16 11:10 UTC, AsPulse commented on sutera/11-Why-sutera-need-to-maintain-idempotence.md
> +しかし、冪等性を保たなければ他人を偽装した操作(リプレイ攻撃など)の危険性があります。
```suggestion
しかし、Suteraネットワークでは多くのコンポーネントが情報を保持・中継する上、認証を行う中央サーバーが存在しないために、電子署名以外にリクエストの正当性を保つ手段をもちません。  
そのため、まったく内容の同じリクエストならば電子署名を使い回すことが可能であり、リプレイ攻撃などが成立します。
 (リプレイ攻撃とは標的が送信した情報を入手し、その情報を再送信することで不正なアクセスを実現する攻撃手法です。[2] )
```
ここもうちょっと説明詳しくしてほしいな！
ついでに、リプレイ攻撃の説明もここにうつしましょう
Suggestionの通りでもいいし、もうちょっと膨らませてもいいよ

2024-07-16 11:10 UTC, AsPulse commented on sutera/11-Why-sutera-need-to-maintain-idempotence.md
> +そのため電子署名にバージョン情報を追加することで冪等性を保っています。
う～ん、どちらかといえば「仕様に対して羃等性という制限を課している」のであって、
バージョン情報がなくても羃等であればいいからなぁ……！
```suggestion
そのためSuteraネットワーク内での全ての通信仕様は、羃等性を保つとともに、任意のタイミングで過去のメッセージが送信されることによる悪意ある攻撃に耐性を持つ必要があります。
```

2024-07-16 11:10 UTC, AsPulse commented on sutera/11-Why-sutera-need-to-maintain-idempotence.md
> +Suteraで冪等性が維持されない場合の例としてリプレイ攻撃があります。リプレイ攻撃とは標的が送信した情報を入手し、その情報を再送信することで不正なアクセスを実現する攻撃手法です。[2]
```suggestion
Suteraネットワーク内で頻繁に行われる「特定のユーザーが保持しているファイルの内容更新」を例に、リプレイ攻撃が有効となるような通信仕様を考えてみましょう。
```

2024-07-16 11:10 UTC, AsPulse commented on sutera/11-Why-sutera-need-to-maintain-idempotence.md
> +このように、電子署名にバージョン情報を追加すると同じファイルを複数回送信しても処理されないため冪等性が保たれていると言えます。
```suggestion
このように、電子署名にバージョン情報を追加することで、同じ通信が複数回送信されても過去のバージョンに対する通信であることを認識でき、現在の状態を変更することはないため、冪等性が保たれていると言えます。  
```
同じファイルを複数回送信しても処理されない、というのは「安全」ってやつなので
微妙に表現を訂正したほうがよいでしょう

2024-07-16 13:35 UTC, slotsu0809 commented on sutera/11-Why-sutera-need-to-maintain-idempotence.md
> +そのため電子署名にバージョン情報を追加することで冪等性を保っています。
冪等性を保つことでリプレイ攻撃などに耐性を持つことができる、と認識しているのですがあっていますか？

2024-07-17 12:42 UTC, slotsu0809 commented
@AsPulse 
修正かけました！概要の部分の説明をsuggestionから変更した点、冪等性の例が特に大きく変更したところです。また、マークダウンで脚注をつけてそっちにリプレイ攻撃の説明も移動しました。あとはsuggestionのとおりです。

2024-07-17 17:59 UTC, AsPulse requested changes
だいぶよくなりました.ᐟ.ᐟ.ᐟ
あとちょっとだけ直させてください

2024-07-17 17:59 UTC, AsPulse commented on sutera/11-Why-sutera-need-to-maintain-idempotence.md
> +特に何回実行しても結果や応答が変わらない操作を指します。[^3]
```suggestion
特に何回実行しても内部状態が変わらない操作を指します。[^3]  
```

羃等な操作でも、複数回実行すると応答が変化することは考えられます
たとえば、SNSにおいて「ある投稿にいいねをつける」というAPIを考え、これが羃等だと仮定します。
- (i) まだいいねをつけていない投稿に対してはいいねをつける
- (ii) 既にいいねをつけている投稿に対してはいいねをつけたままにする

という挙動になると思います。
この際、いいねをつけるAPIを1回呼びだしても、2回以上呼びだしても、そのユーザーがその投稿にいいねをつけた、という内部状態は変更されません。

だけど、(ii) の場合には「もう既にその投稿にはいいねがついています」という応答をしてもいいわけです。
この場合1回目と2回目以降で応答が変化しますが、内部状態は依然として変更されていません。よって、これでも羃等といえます

2024-07-17 17:59 UTC, AsPulse commented on sutera/11-Why-sutera-need-to-maintain-idempotence.md
> +ここで一番最初に送信したデータを悪意ある第三者が入手して、それを再送します。この場合、第三者が送信したファイルに付加されている電子署名は正常なものなのでサーバ側はこの更新を正常なものとして処理します。
「データ」に電子署名が含まれるかがちょっとだけあいまいですかね……？
もうちょっと言葉を明確にできそうだったらしてみてください

2024-07-17 19:48 UTC, slotsu0809 commented
sugesstionの修正しました。加えて冪等性のある場合の説明に文章が足りなかったので追加しました

2024-07-17 22:46 UTC, AsPulse approved these changes
LGTM!! おつかれさま

2024-07-18 02:03 UTC, See2et commented
Squash and merge!

2024-07-18 02:03 UTC, merged