docs: Add Sutera HTTP documentation
SuteraVR/Specifications pull request #52
Opened 2024-07-17 03:22 UTC by tukiminya

「なぜ Sutera は HTTP にこだわるのか」
について記載をしました！

ひとまずはIssueの文面を踏まえた文章になっているはずです！レビューお願いします！

Link with:
- #23

2024-07-17 11:30 UTC, AsPulse commented
`- close #23` みたいに クローズキーワードつけてください.ᐟ.ᐟ.ᐟ (レビューは私のキャパ的にちょっっとだけ待ってね)

2024-07-19 10:24 UTC, tukiminya commented
オートレビューをもとに、内容を修正しました！

2024-07-20 08:00 UTC, AsPulse requested changes
オートレビューちゃんと見てくれるのえらすぎて

2024-07-20 08:00 UTC, AsPulse commented on sutera/why-http.md
> +- HTTP 通信のみが可能なランタイム（実行環境）が存在する
HTTP通信のみが可能なランタイムを、安価で簡単に構築できるマネージドサービスが多く存在する みたいな話

ようするにCloudflare Workers/Cloud Runとか、Argo Tunnel(Zero Trust) のいいところを固有名詞出さずに説明したいわけなんだけど……

今のままだとちょっと説明不足かな

2024-07-20 14:29 UTC, tukiminya commented
@AsPulse 
2度目の正直です
お願いします！

2024-07-22 12:05 UTC, AsPulse requested changes
ごめん.ᐟ.ᐟ.ᐟ レビュー遅れたのに文句ばっかでごめんね.ᐟ.ᐟ.ᐟ

まず一つめは、私がレビュー内で説明のために使ってる表現 (「ランタイム・コスパ・複数のサーバー」みたいな) のが、仕様書に適した表現とは限らなくて……Writerの方にはそこらへんの適切な言葉を探したり、仕様書ないの既存の表現と合わせたりなども含めてお願いしたいです.ᐟ.ᐟ.ᐟ

二つめはHTTPにこだわる理由  = 「Bloomを多くの人が手軽に建てられるようにするため.ᐟ.ᐟ.ᐟ」ってところがまだスっと入ってこない文章です…… (結論が遠い)

曖昧な指示だにゃあと思ったらちょっと突っこんで見てもらっても大丈夫ではあるけど……
一旦修正がんばってみて.ᐟ.ᐟ.ᐟ 三度目の正直待ってる.ᐟ.ᐟ.ᐟ

2024-07-26 03:26 UTC, tukiminya commented
3度目の正直です！！！！！！！！！

2024-07-29 11:27 UTC, See2et approved these changes
LGTM!

2024-07-29 11:28 UTC, See2et commented
@AsPulse 二重チェックお願いします〜

2024-08-06 12:56 UTC, tukiminya commented
@AsPulse , @See2et 
日本語よわよわだったので出直してきました

2024-08-08 12:06 UTC, See2et approved these changes
バカえぐいドキュメント品質(めちゃくちゃクオリティ高くない???

2024-08-08 12:35 UTC, AsPulse requested changes
通話で指摘しきれなかったところを……！

2024-08-14 14:50 UTC, AsPulse approved these changes
LGTM!!!

2024-08-14 14:53 UTC, See2et approved these changes
TKMN!

2024-08-14 14:54 UTC, merged