docs(idea/core):Re 20_why-is-sutera-a-specifications
SuteraVR/Specifications pull request #73
Opened 2024-10-21 10:52 UTC by See2et

- close #20

2024-10-22 13:05 UTC, AsPulse requested changes

2024-10-22 13:05 UTC, AsPulse commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +そのためには特定の環境や実装に依存しないことが望ましいと私たちは考えており、Suteraを仕様書という抽象化された状態で公開し、誰でも実装できるようにしました。
```suggestion
そのため、特定の団体や人への依存をできる限り回避しようと試みており、これはSutera開発チームへの依存ですら例外ではありません。
仮にSuteraがソフトウェアとして存在していた場合、たとえば利用者のコミュニティでは受け入れられないような変更が提案された時、コミュニティによる意思決定でその変更を止めることはできません。オープンソース・プロジェクトとしてSuteraがGitHub上に公開されていたとしても、その変更を承認するかは事実上そのリポジトリのメンテナに委ねられているからです。
これはSuteraというソフトウェアが、結局Sutera開発チームに振り回されており、依存していることを意味します。
そのような場合にSuteraというソフトウェアをフォークして解決しようとするのは、現実的には互換性の観点から非常に困難です。
Suteraのフォークソフトウェア間、あるいは大本のSuteraとの通信に互換性がなければ、「Suteraというソフトウェアを使っている人同士でも通信できない」とった事態が生じ、やがてまた特定のフォークが支配的となり、ただコミュニティの体力を削りとっていくだけに終わります。

この問題を回避するため、SuteraをSuteraたらしめる、通信における規則や仕様やアイデア等のみを仕様書として中心で管理し、仕様書に従っている限りどんなソフトウェアの間でも通信をできるように設計しています。
これにより、Suteraに複数の実装がコミュニティにより出現しても、常にそれらの互換性が保たれ、「特定の団体に依存したソフトウェアを使うしかない」といった状況を軽減します。

またソフトウェアを制作するあたってはライブラリなど依存関係を多く持つ必要がある一方、仕様としてのSuteraはHTTPプロトコル, TCP/IPプロトコル, JSON, 公開鍵暗号などの既に十分多くの箇所で使用されている安定で持続的、オープンなプロトコルのみに依存しているため、この点でもSutera本体がソフトウェアではなく仕様であることが持続性に貢献しています。
```
説明不足だと思います……加筆しました
必要に応じて取りのぞいてください

2024-10-22 13:05 UTC, AsPulse commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +しかし、Suteraは公開された仕様書にすぎないため、コミュニティの中で実装が生まれていくことによって、Suteraという規格の持続性・汎用性を保ったまま、ユーザが望む形に沿ったSocial-VRを実現し続けることができます。
```suggestion
しかし、Suteraは公開された仕様書にすぎないため、コミュニティの中で実装が生まれていくことによって、Suteraという規格の持続性・汎用性を保ったまま、ユーザが望む形に沿ったSocial-VRを実現しつづけることができます。
```
開いた方がいいかな……まぁどっちでもいいんだけどね……

2024-10-22 13:05 UTC, AsPulse commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +また、複数の実装が存在することでそれらの間に競争が生まれ、コミュニティがより活発になることも期待できるかもしれません。
これ含める必要あるかな……？私はないかな～とも思ったんだけどどうだろ……しぜ判断かも

2024-10-22 13:05 UTC, AsPulse commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +もちろん、ユーザーはSuteraの仕様に準拠する実装を自由に開発することができます。
```suggestion
以下は、Suteraチームが提供するSutera実装の一覧です。
```
最初の指摘と同じで、あんまり対話しない方が……

2024-10-25 02:10 UTC, See2et commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +もちろん、ユーザーはSuteraの仕様に準拠する実装を自由に開発することができます。
しーぜっと、無意識に誰かとお話しながら文章を書く癖があるかも......承知！

2024-10-25 02:16 UTC, See2et commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +そのためには特定の環境や実装に依存しないことが望ましいと私たちは考えており、Suteraを仕様書という抽象化された状態で公開し、誰でも実装できるようにしました。
言語化がうますぎる！！！！！
どれくらいうまいかっていうと、誕生日に食べるショートケーキくらいうまい。

2024-10-25 02:19 UTC, See2et commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +しかし、Suteraは公開された仕様書にすぎないため、コミュニティの中で実装が生まれていくことによって、Suteraという規格の持続性・汎用性を保ったまま、ユーザが望む形に沿ったSocial-VRを実現し続けることができます。
絶妙かも！でもあすぱるチェックに引っかかったなら開いちゃっていいと思います！

2024-10-26 04:43 UTC, See2et commented on 20_why-is-sutera-a-specifications_ja-jp.md
> +また、複数の実装が存在することでそれらの間に競争が生まれ、コミュニティがより活発になることも期待できるかもしれません。
> また、複数の実装が存在することでそれらの間に競争が生まれ、コミュニティがより活発になることも期待できるかもしれません。

私的には最後の一文を削除するのみでいいかなって思ったのでとりあえず反映しました！
直接話しした方がよければ、どっかで通話して議題にあげてもいいかも？

2024-10-28 01:44 UTC, AsPulse approved these changes
ﾖｼ!!!

2024-10-28 13:21 UTC, merged